package come.zhu.com.hushiguang.zhudome.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COLECT".
 */
public class Colect {

    private Long id;
    private String deviceId;
    private String newsId;
    private String image;
    private String title;

    public Colect() {
    }

    public Colect(Long id) {
        this.id = id;
    }

    public Colect(Long id, String deviceId, String newsId, String image, String title) {
        this.id = id;
        this.deviceId = deviceId;
        this.newsId = newsId;
        this.image = image;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
