package come.zhu.com.hushiguang.zhudome.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "COMMENT_PRISE".
 */
public class CommentPrise {

    private Long id;
    private String deviceId;
    private String commentId;

    public CommentPrise() {
    }

    public CommentPrise(Long id) {
        this.id = id;
    }

    public CommentPrise(Long id, String deviceId, String commentId) {
        this.id = id;
        this.deviceId = deviceId;
        this.commentId = commentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getCommentId() {
        return commentId;
    }

    public void setCommentId(String commentId) {
        this.commentId = commentId;
    }

}
