package come.zhu.com.hushiguang.zhudome.DB;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig colectDaoConfig;
    private final DaoConfig themesDaoConfig;
    private final DaoConfig storePriseDaoConfig;
    private final DaoConfig commentPriseDaoConfig;

    private final ColectDao colectDao;
    private final ThemesDao themesDao;
    private final StorePriseDao storePriseDao;
    private final CommentPriseDao commentPriseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        colectDaoConfig = daoConfigMap.get(ColectDao.class).clone();
        colectDaoConfig.initIdentityScope(type);

        themesDaoConfig = daoConfigMap.get(ThemesDao.class).clone();
        themesDaoConfig.initIdentityScope(type);

        storePriseDaoConfig = daoConfigMap.get(StorePriseDao.class).clone();
        storePriseDaoConfig.initIdentityScope(type);

        commentPriseDaoConfig = daoConfigMap.get(CommentPriseDao.class).clone();
        commentPriseDaoConfig.initIdentityScope(type);

        colectDao = new ColectDao(colectDaoConfig, this);
        themesDao = new ThemesDao(themesDaoConfig, this);
        storePriseDao = new StorePriseDao(storePriseDaoConfig, this);
        commentPriseDao = new CommentPriseDao(commentPriseDaoConfig, this);

        registerDao(Colect.class, colectDao);
        registerDao(Themes.class, themesDao);
        registerDao(StorePrise.class, storePriseDao);
        registerDao(CommentPrise.class, commentPriseDao);
    }
    
    public void clear() {
        colectDaoConfig.getIdentityScope().clear();
        themesDaoConfig.getIdentityScope().clear();
        storePriseDaoConfig.getIdentityScope().clear();
        commentPriseDaoConfig.getIdentityScope().clear();
    }

    public ColectDao getColectDao() {
        return colectDao;
    }

    public ThemesDao getThemesDao() {
        return themesDao;
    }

    public StorePriseDao getStorePriseDao() {
        return storePriseDao;
    }

    public CommentPriseDao getCommentPriseDao() {
        return commentPriseDao;
    }

}
