package come.zhu.com.hushiguang.zhudome.DB;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "THEMES".
 */
public class Themes {

    private Long id;
    private String deviceId;
    private String themesId;

    public Themes() {
    }

    public Themes(Long id) {
        this.id = id;
    }

    public Themes(Long id, String deviceId, String themesId) {
        this.id = id;
        this.deviceId = deviceId;
        this.themesId = themesId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getThemesId() {
        return themesId;
    }

    public void setThemesId(String themesId) {
        this.themesId = themesId;
    }

}
